version: '3.7'

services:
  redis_test:
    container_name: redis_test
    image: redis:5
  mysql_test:
    container_name: mysql_test
    image: mysql:5.7
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - '${LOCALSTACK_PORT}:${LOCALSTACK_PORT}'
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DEFAULT_REGION=${LOCALSTACK_REGION}
      - EDGE_PORT=${LOCALSTACK_PORT}
    volumes:
      - '${LOCALSTACK_TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
