version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    networks:
      - webnet
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
networks:
  webnet:
volumes:
  mysql-data:
