version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    networks:
      - webnet
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - '${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}'
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic
  es02:
    container_name: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    container_name: es03
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic
  local-sqs:
    container_name: local-sqs
    image: greatsumini/local-sqs:0.1.1
    networks:
      - webnet
    ports:
      - '${LOCAL_SQS_PORT}:${LOCAL_SQS_PORT}'
networks:
  webnet:
  elastic:
    driver: bridge
volumes:
  mysql-data:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
