module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '@src/(.*)$': '<rootDir>/$1',
    '@auth/(.*)$': ['<rootDir>/auth/$1'],
    '@batch/(.*)$': ['<rootDir>/batch/$1'],
    '@config/(.*)$': ['<rootDir>/config/$1'],
    '@common/(.*)$': ['<rootDir>/common/$1'],
    '@jobs/(.*)$': ['<rootDir>/jobs/$1'],
    '@providers/(.*)$': ['<rootDir>/providers/$1'],
    '@queue/(.*)$': ['<rootDir>/queue/$1'],
    '@templates/(.*)$': ['<rootDir>/templates/$1'],
    '@admin/(.*)$': '<rootDir>/modules/admin/$1',
    '@mcommon/(.*)$': '<rootDir>/modules/common/$1',
    '@content/(.*)$': '<rootDir>/modules/content/$1',
    '@exhibition/(.*)$': '<rootDir>/modules/exhibition/$1',
    '@item/(.*)$': '<rootDir>/modules/item/$1',
    '@my/(.*)$': '<rootDir>/modules/my/$1',
    '@order/(.*)$': '<rootDir>/modules/order/$1',
    '@payment/(.*)$': '<rootDir>/modules/payment/$1',
    '@user/(.*)$': '<rootDir>/modules/user/$1',
  },
};
