export const UPDATE_SELLER_ITEMS_JOB = 'UPDATE_SELLER_ITEMS_JOB';
export const UPDATE_ITEM_IS_SOLDOUT_JOB = 'UPDATE_ITEM_IS_SOLDOUT_JOB';
export const UPDATE_ITEM_SCORE_JOB = 'UPDATE_ITEM_SCORE_JOB';
