-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDcofKY5wzdrvfaFK
OpADZzymj7dAUFvXRZa0XIGoJuegCgYIKoZIzj0DAQehRANCAATtuW+gPYtbt+yC
US2Gu1UaVghYdcH1UEmBUMoJWjXLyZ8nkbUPJZttalnqi0HmpohjAZ0D0bdRqZUB
sMh9VNUA
-----END PRIVATE KEY-----