export const INDEX_DIGESTS_JOB = 'INDEX_DIGESTS';
export const INDEX_ITEMS_JOB = 'INDEX_ITEMS';
export const INDEX_LOOKS_JOB = 'INDEX_LOOKS';
export const INDEX_VIDEOS_JOB = 'INDEX_VIDEOS';
export const INDEX_ORDER_ITEMS_JOB = 'INDEX_ORDER_ITEMS';
export const INDEX_REFUND_REQUESTS_JOB = 'INDEX_REFUND_REQUESTS_JOB';
