export const SCRAP_SELLER_ITEMS_QUEUE = 'S2S-SCRAP_SELLER_ITEMS';
export const PROCESS_SELLER_ITEMS_SCRAP_RESULT_QUEUE =
  'S2I-PROCESS_SELLER_ITEMS_SCRAP_RESULT';

export const REMOVE_EXPECTED_POINT_EVENT_QUEUE =
  'P2P-REMOVE_EXPECTED_POINT_EVENT';

export const UPDATE_ITEM_IMAGE_URL_QUEUE = 'I2I-UPDATE_ITEM_IMAGE_URL';
