export const SCRAP_SELLER_ITEMS_QUEUE = 'S2S-SCRAP_SELLER_ITEMS';
export const PROCESS_SELLER_ITEMS_SCRAP_RESULT_QUEUE =
  'S2I-PROCESS_SELLER_ITEMS_SCRAP_RESULT';

export const REMOVE_EXPECTED_POINT_EVENT_QUEUE =
  'P2P-REMOVE_EXPECTED_POINT_EVENT';

export const UPDATE_ITEM_IMAGE_URL_QUEUE = 'I2I-UPDATE_ITEM_IMAGE_URL';
export const UPDATE_ITEM_DETAIL_IMAGES_QUEUE = 'I2I-UPDATE_ITEM_DETAIL_IMAGES';

export const UPDATE_COMMENT_LIKE_COUNT_QUEUE = 'L2C-UPDATE_COMMENT_LIKE_COUNT';
export const UPDATE_DIGEST_LIKE_COUNT_QUEUE = 'L2D-UPDATE_DIGEST_LIKE_COUNT';
export const UPDATE_LOOK_LIKE_COUNT_QUEUE = 'L2L-UPDATE_LOOK_LIKE_COUNT';
export const UPDATE_VIDEO_LIKE_COUNT_QUEUE = 'L2V-UPDATE_VIDEO_LIKE_COUNT';
export const UPDATE_KEYWORD_LIKE_COUNT_QUEUE = 'L2K-UPDATE_KEYWORD_LIKE_COUNT';

export const UPDATE_USER_FOLLOW_COUNT_QUEUE = 'F2U-UPDATE_USER_FOLLOW_COUNT';

export const UPDATE_KEYWORD_CLASS_OWNING_COUNT_CACHE_QUEUE =
  'O2O-UPDATE_KEYWORD_CLASS_OWNING_COUNT_CACHE';

export const RESTORE_DEDUCTED_PRODUCT_STOCK_QUEUE =
  'O2P-RESTORE_DEDUCTED_PRODUCT_STOCK';

export const UPDATE_DIGEST_COMMENT_COUNT_QUEUE =
  'C2D-UPDATE_DIGEST_COMMENT_COUNT';
export const UPDATE_LOOK_COMMENT_COUNT_QUEUE = 'C2L-UPDATE_LOOK_COMMENT_COUNT';
export const UPDATE_VIDEO_COMMENT_COUNT_QUEUE =
  'C2V-UPDATE_VIDEO_COMMENT_COUNT';

export const UPDATE_ITEM_DIGEST_STATISTICS_QUEUE =
  'D2I-UPDATE_ITEM_DIGEST_STATISTICS';

export const SEND_CANCEL_ORDER_APPROVED_ALIMTALK_QUEUE =
  'O2O-SEND_CANCEL_ORDER_APPROVED_ALIMTALK';

export const PROCESS_VBANK_PAID_ORDER_QUEUE = 'I2O-PROCESS_VBANK_PAID_ORDER';

export const SEND_VBANK_PAID_ALIMTALK_QUEUE = 'I2O-SEND_VBANK_PAID_ALIMTALK';
export const SEND_ORDER_COMPLETED_ALIMTALK_QUEUE =
  'O2O-SEND_ORDER_COMPLETED_ALIMTALK';
export const SEND_REFUND_REQUESTED_ALIMTALK_QUEUE =
  'O2O-SEND_REFUND_REQUESTED_ALIMTALK';
export const SEND_EXCHANGE_ITEM_RESHIPED_ALIMTALK_QUEUE =
  'E2E-SEND_EXCHANGE_ITEM_RESHIPED_ALIMTALK';
export const SEND_EXCHANGE_REQUESTED_ALIMTALK_QUEUE =
  'O2O-SEND_EXCHANGE_REQUESTED_ALIMTALK';
export const SEND_INQUIRY_ANSWERED_ALIMTALK_QUEUE =
  'I2I-SEND_INQUIRY_ANSWERED_ALIMTALK';
export const SEND_INQUIRY_CREATED_ALIMTALK_QUEUE =
  'I2I-SEND_INQUIRY_CREATED_ALIMTALK_MESSAGE';

export const SEND_INQUIRY_CREATION_SLACK_MESSAGE_QUEUE =
  'I2I-SEND_INQUIRY_CREATION_SLACK_MESSAGE';
export const SEND_ITEM_CREATION_SUCCESS_SLACK_MESSAGE_QUEUE =
  'I2I-SEND_ITEM_CREATION_SUCCESS_SLACK_MESSAGE';
export const SEND_ITEM_CREATION_FAIL_SLACK_MESSAGE_QUEUE =
  'I2I-SEND_ITEM_CREATION_FAIL_SLACK_MESSAGE';

export const REMOVE_DIGEST_IMAGES_QUEUE = 'D2D-REMOVE_DIGEST_IMAGES';
export const REMOVE_DIGESTS_QUEUE = 'D2D-REMOVE_DIGESTS';
export const REMOVE_LOOK_IMAGES_QUEUE = 'L2L-REMOVE_LOOK_IMAGES';

export const SEND_DIGEST_CREATION_SLACK_MESSAGE_QUEUE =
  'D2D-SEND_DIGEST_CREATION_SLACK_MESSAGE';
export const SEND_LOOK_CREATION_SLACK_MESSAGE_QUEUE =
  'L2L-SEND_LOOK_CREATION_SLACK_MESSAGE';
export const SEND_VIDEO_CREATION_SLACK_MESSAGE_QUEUE =
  'V2V-SEND_VIDEO_CREATION_SLACK_MESSAGE';

export const SAVE_BUYER_INFO_QUEUE = 'O2U-SAVE_BUYER_INFO';

export const GIVE_REWARD_QUEUE = 'O2R-GIVE_REWARD';

export const INDEX_ORDER_ITEMS_QUEUE = 'O2O-INDEX_ORDER_ITEMS';
export const DELETE_ORDER_ITEMS_INDEX_QUEUE = 'O2O-DELETE_ORDER_ITEMS_INDEX';

export const INDEX_REFUND_REQUESTS_QUEUE = 'R2R-INDEX_REFUND_REQUESTS';
export const INDEX_EXCHANGE_REQUESTS_QUEUE = 'E2E-INDEX_EXCHANGE_REQUESTS';
export const INDEX_INQUIRY_QUEUE = 'I2I-INDEX_INQUIRY';
export const REMOVE_INQUIRY_INDEX_QUEUE = 'I2I-REMOVE_INQUIRY_INDEX';

export const SEND_EXCHANGE_CANCELED_ALIMTALK_QUEUE =
  'E2E-SEND_EXCHANGE_CANCELED_ALIMTALK';

export const UPDATE_YOUTUBE_VIDEO_DATAS_QUEUE =
  'V2V-UPDATE_YOUTUBE_VIDEO_DATAS';
