export const SCRAP_SELLER_ITEMS_QUEUE = 'S2S-SCRAP_SELLER_ITEMS';
export const PROCESS_SELLER_ITEMS_SCRAP_RESULT_QUEUE =
  'S2I-PROCESS_SELLER_ITEMS_SCRAP_RESULT';

export const REMOVE_EXPECTED_POINT_EVENT_QUEUE =
  'P2P-REMOVE_EXPECTED_POINT_EVENT';

export const UPDATE_ITEM_IMAGE_URL_QUEUE = 'I2I-UPDATE_ITEM_IMAGE_URL';

export const UPDATE_COMMENT_LIKE_COUNT_QUEUE = 'L2C-UPDATE_COMMENT_LIKE_COUNT';
export const UPDATE_DIGEST_LIKE_COUNT_QUEUE = 'L2D-UPDATE_DIGEST_LIKE_COUNT';
export const UPDATE_LOOK_LIKE_COUNT_QUEUE = 'L2L-UPDATE_LOOK_LIKE_COUNT';
export const UPDATE_VIDEO_LIKE_COUNT_QUEUE = 'L2V-UPDATE_VIDEO_LIKE_COUNT';
export const UPDATE_KEYWORD_LIKE_COUNT_QUEUE = 'L2K-UPDATE_KEYWORD_LIKE_COUNT';

export const UPDATE_USER_FOLLOW_COUNT_QUEUE = 'F2U-UPDATE_USER_FOLLOW_COUNT';

export const UPDATE_KEYWORD_CLASS_OWNING_COUNT_CACHE_QUEUE =
  'O2O-UPDATE_KEYWORD_CLASS_OWNING_COUNT_CACHE';

export const RESTORE_DEDUCTED_PRODUCT_STOCK_QUEUE =
  'O2P-RESTORE_DEDUCTED_PRODUCT_STOCK';

export const UPDATE_DIGEST_COMMENT_COUNT_QUEUE =
  'C2D-UPDATE_DIGEST_COMMENT_COUNT';
export const UPDATE_LOOK_COMMENT_COUNT_QUEUE = 'C2L-UPDATE_LOOK_COMMENT_COUNT';
export const UPDATE_VIDEO_COMMENT_COUNT_QUEUE =
  'C2V-UPDATE_VIDEO_COMMENT_COUNT';
