export const PROCESS_DELAYED_ORDER_ITEMS_JOB =
  'PROCESS_DELAYED_ORDER_ITEMS_JOB';
export const PROCESS_DELAYED_EXCHANGE_REQUESTS_JOB =
  'PROCESS_DELAYED_EXCHANGE_REQUESTS_JOB';
export const PROCESS_DELAYED_REFUND_REQUESTS_JOB =
  'PROCESS_DELAYED_REFUND_REQUESTS_JOB';
export const SEND_DELAYED_ORDER_ITEMS_ALIMTALK_JOB =
  'SEND_DELAYED_ORDER_ITEMS_ALIMTALK_JOB';
export const SEND_DELAYED_EXCHANGE_REQUESTS_ALIMTALK_JOB =
  'SEND_DELAYED_EXCHANGE_REQUESTS_ALIMTALK_JOB';
export const SEND_DELAYED_REFUND_REQUESTS_ALIMTALK_JOB =
  'SEND_DELAYED_REFUND_REQUESTS_ALIMTALK_JOB';
export const CONFIRM_ORDER_ITEMS_JOB = 'CONFIRM_ORDER_ITEMS_JOB';
export const REMOVE_EXPIRED_ORDERS_JOB = 'REMOVE_EXPIRED_ORDERS_JOB';
export const REMOVE_PAYING_ORDERS_JOB = 'REMOVE_PAYING_ORDERS_JOB';
export const SEND_ORDERS_CREATED_ALIMTALK_JOB =
  'SEND_ORDERS_CREATED_ALIMTALK_JOB';
