export const PROCESS_DELAYED_ORDER_ITEMS_JOB =
  'PROCESS_DELAYED_ORDER_ITEMS_JOB';
export const PROCESS_DELAYED_EXCHANGE_REQUESTS_JOB =
  'PROCESS_DELAYED_EXCHANGE_REQUESTS_JOB';
export const PROCESS_DELAYED_REFUND_REQUESTS_JOB =
  'PROCESS_DELAYED_REFUND_REQUESTS_JOB';
