export enum ItemSizeChartColumnName {
  name = 'name',
  totalLength = 'totalLength',
  shoulderWidth = 'shoulderWidth',
  chestWidth = 'chestWidth',
  sleeveLength = 'sleeveLength',
  waistWidth = 'waistWidth',
  riseHeight = 'riseHeight',
  thighWidth = 'thighWidth',
  hemWidth = 'hemWidth',
  accWidth = 'accWidth',
  accHeight = 'accHeight',
  accDepth = 'accDepth',
  crossStrapLength = 'crossStrapLength',
  watchBandDepth = 'watchBandDepth',
  glassWidth = 'glassWidth',
  glassBridgeLength = 'glassBridgeLength',
  glassLegLength = 'glassLegLength',
}
