export enum PredefinedCategoryCode {
  Outer = 'OUTER',
  Top = 'TOP',
  Shoes = 'SHOES',
  Bag = 'BAG',
  Accessory = 'ACCESSORY',
  Bottom = 'BOTTOM',
  //outer,top
  LeatherJacket = 'LEATHER_JACKET',
  Blaser = 'BLAZER',
  TranchCoat = 'TRENCH_COAT',
  Cardigan = 'CARDIGAN',
  Coat = 'COAT',
  Jacket = 'JACKET',
  Jumper = 'JUMPER',
  Padding = 'PADDING',
  Vest = 'VEST',
  ShortTshirt = 'SHORT_TSHIRT',
  LongTshirt = 'LONG_TSHIRT',
  Shirt = 'SHIRT',
  Knit = 'KNIT',
  Sweatshirt = 'SWEATSHIRT',
  Hood = 'HOOD',
  Sleeveless = 'SLEEVELESS',
  //bottom
  DenimPants = 'DENIM_PANTS',
  CottonPants = 'COTTON_PANTS',
  TraningPants = 'TRAINING_PANTS',
  ShortPants = 'SHORT_PANTS',
  Overalls = 'OVERALLS',
  Slacks = 'SLACKS',
  //shoes
  Sneakers = 'SNEAKERS',
  RunningShoes = 'RUNNING_SHOES',
  DressShoes = 'DRESS_SHOES',
  Boots = 'BOOTS',
  Sandal = 'SANDAL',
  Slipper = 'SLIPPER',
  DerbyDressShoes = 'DERBY_DRESS_SHOES',
  LoaferDressShoes = 'LOAFER_DRESS_SHOES',
  ChelseaBoots = 'CHELSEA_BOOTS',
  WalkerBoots = 'WALKER_BOOTS',
  EtcBoots = 'ETC_BOOTS',
  //bag
  Backpack = 'BACKPACK',
  ShoulderBag = 'SHOULDER_BAG',
  CrossBag = 'CROSS_BAG',
  Carrier = 'CARRIER',
  WaistBag = 'WAIST_BAG',
  ClutchPouch = 'CLUTCH_POUCH',
  EtcBag = 'ETC_BAG',
  BostonBag = 'BOSTON_BAG',
  //accessory
  Hat = 'HAT',
  Watch = 'WATCH',
  Wallet = 'WALLET',
  Belt = 'BELT',
  Glasses = 'GLASSES',
  Sunglasses = 'SUNGLASSES',
  Muffler = 'MUFFLER',
  Jewelry = 'JEWELRY',
  EtcAccessory = 'ETC_ACCESSORY',
}
