export enum PredefinedCategoryCode {
  Outer = 'OUTER',
  Top = 'TOP',
  Bottom = 'BOTTOM',
  Shoes = 'SHOES',
  Bag = 'BAG',
  Acc = 'ACC',
  // outer
  LeatherJacket = 'LEATHER_JACKET',
  Blazer = 'BLAZER',
  TruckerJacket = 'TRUCKER_JACKET',
  CoachJacket = 'COACH_JACKET',
  LightCoat = 'LIGHT_COAT',
  HeavyCoat = 'HEAVY_COAT',
  Blouson = 'BLOUSON',
  Fleece = 'FLEECE',
  Cardigan = 'CARDIGAN',
  Padding = 'PADDING',
  Vest = 'VEST',
  EtcOuter = 'ETC_OUTER',
  // top
  ShortTshirt = 'SHORT_TSHIRT',
  LongTshirt = 'LONG_TSHIRT',
  Shirt = 'SHIRT',
  Knit = 'KNIT',
  Sweatshirt = 'SWEATSHIRT',
  Hood = 'HOOD',
  Sleeveless = 'SLEEVELESS',
  //bottom
  DenimPants = 'DENIM_PANTS',
  CottonPants = 'COTTON_PANTS',
  TraningPants = 'TRAINING_PANTS',
  ShortPants = 'SHORT_PANTS',
  Slacks = 'SLACKS',
  //shoes
  Canvas = 'CANVAS',
  RunningShoes = 'RUNNING_SHOES',
  DressShoes = 'DRESS_SHOES',
  Boots = 'BOOTS',
  Loafer = 'LOAFER',
  SandalSlipper = 'SANDAL_SLIPPER',
  EtcShoes = 'ETC_SHOES',
  //bag
  Backpack = 'BACKPACK',
  ShoulderBag = 'SHOULDER_BAG',
  CrossBag = 'CROSS_BAG',
  ClutchPouch = 'CLUTCH_POUCH',
  EtcBag = 'ETC_BAG',
  //accessory
  Hat = 'HAT',
  Belt = 'BELT',
  Muffler = 'MUFFLER',
  Watch = 'WATCH',
  Sunglasses = 'SUNGLASSES',
  Braclet = 'BRACLET',
  Ring = 'RING',
  Necklace = 'NECKLACE',
  Grooming = 'GROOMING',
  EtcAcc = 'ETC_ACC',
}
